name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: gtsosu

    steps:
      - env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          DEV_MONGO_SRV: ${{ secrets.DEV_MONGO_SRV }}
          OSU_API_KEY: ${{ secrets.OSU_API_KEY }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: echo $TEST_VAR
      - run: npm ci
      - run: npm run build
      - run: npm test
